In [6]:
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import time
col = ['JOB_TITLE', 'JOB_CATERGORY', 'LOCATION', 'STATE','JOB ID']
sample_df = pd.DataFrame(columns = col) #to create the empty dataframe
print(sample_df)
page = requests.get("https://careers.ibm.com/ListJobs/All/Search/Country/IN//?lang=en")
soup = BeautifulSoup(page.text, 'html.parser')
for  t in  soup.find_all(name='table', attrs={'class':'JobListTable'}): 
    job_post=[]
    g=t.find_all(name='td', attrs={'class':'coloriginaljobtitle'})
    for i in range(len(g)):
        s=str(g[i]).replace("</a>"," ")
        s1=s.replace("</td>"," ")
        s2=s1[s1.rfind(">")+1:] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    sample_df['JOB_TITLE']=job_post
    job_post=[]
    m=(t.find_all(name='td',attrs={'class':'colshorttextfield1'}))
    if len(m) > 0:
            for b in m:
                    job_post.append(b.text.strip())
    sample_df['JOB_CATERGORY']=job_post
    job_post=[]
    n=(t.find_all(name='td',attrs={'class':'colshorttextfield19'}))
    if len(n) > 0:
            for b in n:
                    job_post.append(b.text.strip())
    sample_df['LOCATION']=job_post
    job_post=[]
    o=(t.find_all(name='td',attrs={'class':'colcity'}))
    if len(o) > 0:
            for b in o:
                    job_post.append(b.text.strip())
    sample_df['STATE']=job_post
    job_post=[]
    p=(t.find_all(name='td',attrs={'class':'coldisplayjobid'}))
    if len(p) > 0:
            for b in p:
                    job_post.append(b.text.strip())
    sample_df['JOB_ID']=job_post

print(sample_df)

Empty DataFrame
Columns: [JOB_TITLE, JOB_CATERGORY, LOCATION, STATE, JOB ID]
Index: []
                                            JOB_TITLE  \
0                                  Cognos Developer
1           Technical Support - Linux administrator
2                               Mainframe Developer
3                  Full Stack Application Developer
4                  Full Stack Application Developer
5   Senior Practitioner - Finance and Administrati...
6   Professional - Finance and Administration Deli...
7        Lead - Finance and Administration Delivery
8                  Full Stack Application Developer
9                          Automation Test Engineer
10  Package Consultant: Workday Benefits &amp; Com...
11                                   EDI Consultant
12     Data Engineer: Enterprise Content Management
13             Application Developer: Microservices
14  Associate Director â€“ Contact Center Solutions ...
15                          Fraud Analyst_IBM Cloud
16            Application Developer: Microsoft .NET
17  Package Consultant: Workday HCM &amp; Compensa...
18                     Security Firewall Specialist
19                           Technical Professional
20                          Designer: Visual Design
21                          Designer: Visual Design
22                 Package Specialist: SAP Security
23             Mainframe DB2 Database Administrator
24  Senior Practitioner - Finance and Administrati...
25        Integration Architect: Hybrid Integration
26  Practitioner - Finance and Administration Deli...
27                              MySQL Administrator
28                              MySQL Administrator
29       Lead - Finance and Administration Delivery

                     JOB_CATERGORY     LOCATION            STATE JOB ID  \
0   Software Development & Support    KARNATAKA        Bangalore    NaN
1             Technical Specialist    KARNATAKA        Bangalore    NaN
2   Software Development & Support    KARNATAKA        Bangalore    NaN
3   Software Development & Support    TELANGANA        Hyderabad    NaN
4   Software Development & Support    KARNATAKA        Bangalore    NaN
5                          Finance    KARNATAKA        Bangalore    NaN
6                          Finance    KARNATAKA        Bangalore    NaN
7                          Finance    KARNATAKA        Bangalore    NaN
8   Software Development & Support    KARNATAKA        Bangalore    NaN
9   Software Development & Support    KARNATAKA        BANGALORE    NaN
10                      Consultant  WEST BENGAL          Kolkata    NaN
11  Software Development & Support    KARNATAKA        Bangalore    NaN
12            Technical Specialist  MAHARASHTRA           Mumbai    NaN
13            Technical Specialist    KARNATAKA        Bangalore    NaN
14                         Finance     MULTIPLE  MULTIPLE CITIES    NaN
15            Technical Specialist    TELANGANA        Hyderabad    NaN
16            Technical Specialist  MAHARASHTRA             Pune    NaN
17                      Consultant    KARNATAKA        Bangalore    NaN
18           Enterprise Operations    KARNATAKA        Bangalore    NaN
19            Technical Specialist    KARNATAKA        Bangalore    NaN
20                          Design    KARNATAKA        Bangalore    NaN
21                          Design    KARNATAKA        Bangalore    NaN
22            Technical Specialist  MAHARASHTRA             PUNE    NaN
23            Technical Specialist    KARNATAKA        Bangalore    NaN
24                         Finance   TAMIL NADU          Chennai    NaN
25                       Architect    KARNATAKA        Bangalore    NaN
26                         Finance    KARNATAKA        Bangalore    NaN
27            Technical Specialist    KARNATAKA        Bangalore    NaN
28            Technical Specialist    KARNATAKA        Bangalore    NaN
29                         Finance   TAMIL NADU          Chennai    NaN

      JOB_ID
0   328736BR
1   328137BR
2   328093BR
3   327317BR
4   326880BR
5   333045BR
6   333036BR
7   333051BR
8   330473BR
9   323647BR
10  333059BR
11  333257BR
12  333544BR
13  333902BR
14  333915BR
15  333938BR
16  332909BR
17  332880BR
18  331012BR
19  328469BR
20  333696BR
21  333382BR
22  308395BR
23  333869BR
24  333786BR
25  333668BR
26  332237BR
27  332345BR
28  332346BR
29  332376BR

In [35]:
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import time
col = ['JOB_TITLE','REQUISTION ID','POSTED DATE']
sample_df = pd.DataFrame(columns = col)
page = requests.get("https://jobs.ltts.com/go/INDIA/4590610/?q=&sortColumn=referencedate&sortDirection=desc")
soup = BeautifulSoup(page.text, 'html.parser')
for t in soup.find_all(name='table',attrs={'id':'searchresults'}):
    k=t.find_all(name='span',attrs={'class':'jobTitle hidden-phone'})
    job_post=[]
    for i in range(len(k)):
        s=str(k[i]).replace("</a>","")
        s1=s.replace("</span>","")
        s2=s1[s1.rfind(">")+1:] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    sample_df['JOB_TITLE']=job_post
    job_post=[]
    l=t.find_all(name='span',attrs={'class':'jobFacility'})
    for i in range(1,len(l)):
        s=str(l[i]).replace("</a>","")
        s1=s.replace("</span>","")
        s2=s1[s1.rfind(">")+1:] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    res = [] 
    [res.append(x) for x in job_post if x not in res] 
    sample_df['REQUISTION ID']=res
    n=t.find_all(name='span',attrs={"class":'jobDate'})
    job_post=[]
    for i in range(1,len(n),2):
        s=str(n[i]).replace("</a>","")
        s1=s.replace("</span>","")
        s2=s1[s1.rfind(">")+1:s1.find('\t')] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    sample_df['POSTED DATE']=job_post
print(sample_df)
page1 = requests.get("https://jobs.ltts.com/go/INDIA/4590610/5/?q=&sortColumn=referencedate&sortDirection=desc")
soup1 = BeautifulSoup(page1.text, 'html.parser')
for t in soup1.find_all(name='table',attrs={'id':'searchresults'}):
    k=t.find_all(name='span',attrs={'class':'jobTitle hidden-phone'})
    job_post=[]
    for i in range(len(k)):
        s=str(k[i]).replace("</a>","")
        s1=s.replace("</span>","")
        s2=s1[s1.rfind(">")+1:] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    sample_df['JOB_TITLE']=job_post
    job_post=[]
    l=t.find_all(name='span',attrs={'class':'jobFacility'})
    for i in range(1,len(l)):
        s=str(l[i]).replace("</a>","")
        s1=s.replace("</span>","")
        s2=s1[s1.rfind(">")+1:] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    res = [] 
    [res.append(x) for x in job_post if x not in res] 
    sample_df['REQUISTION ID']=res
    n=t.find_all(name='span',attrs={"class":'jobDate'})
    job_post=[]
    for i in range(1,len(n),2):
        s=str(n[i]).replace("</a>","")
        s1=s.replace("</span>","")
        s2=s1[s1.rfind(">")+1:s1.find('\t')] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    sample_df['POSTED DATE']=job_post
print(sample_df)
page2 = requests.get("https://jobs.ltts.com/go/INDIA/4590610/10/?q=&sortColumn=referencedate&sortDirection=desc")
soup2 = BeautifulSoup(page2.text, 'html.parser')
for t in soup2.find_all(name='table',attrs={'id':'searchresults'}):
    k=t.find_all(name='span',attrs={'class':'jobTitle hidden-phone'})
    job_post=[]
    for i in range(len(k)):
        s=str(k[i]).replace("</a>","")
        s1=s.replace("</span>","")
        s2=s1[s1.rfind(">")+1:] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    sample_df['JOB_TITLE']=job_post
    job_post=[]
    l=t.find_all(name='span',attrs={'class':'jobFacility'})
    for i in range(1,len(l)):
        s=str(l[i]).replace("</a>","")
        s1=s.replace("</span>","")
        s2=s1[s1.rfind(">")+1:] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    res = [] 
    [res.append(x) for x in job_post if x not in res] 
    sample_df['REQUISTION ID']=res
    n=t.find_all(name='span',attrs={"class":'jobDate'})
    job_post=[]
    for i in range(1,len(n),2):
        s=str(n[i]).replace("</a>","")
        s1=s.replace("</span>","")
        s2=s1[s1.rfind(">")+1:s1.find('\t')] 
        s3=s2.replace("\n","")
        job_post.append(s3)
    sample_df['POSTED DATE']=job_post
print(sample_df)

                 JOB_TITLE REQUISTION ID   POSTED DATE
0        ReactJS Developer        132821   Oct 1, 2020
1          Senior Engineer        121222  Sep 30, 2020
2    Senior Engineer - C++        122183  Sep 29, 2020
3  Sr. .Net Core Developer        123383  Sep 28, 2020
4  C# Full Stack developer        129381  Sep 28, 2020
                                   JOB_TITLE REQUISTION ID   POSTED DATE
0                  C# .NET Backend Developer        129261  Sep 28, 2020
1                    Azure .Net C# Developer        130903  Sep 28, 2020
2                       RTM Python Developer        124363  Sep 28, 2020
3  Senior Unity 3D and C# script Android App        122263  Sep 28, 2020
4  Senior Unity 3D and C# script Android App        122281  Sep 28, 2020
                             JOB_TITLE REQUISTION ID   POSTED DATE
0                  Front End Developer        124941  Sep 28, 2020
1             Python Developer Support        123682  Sep 28, 2020
2  Senior Clinical Documetation Expert        128125  Sep 28, 2020
3                    Xamarin Developer        130901  Sep 28, 2020
4                      Senior Engineer        120561  Sep 26, 2020

In [73]:
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import time
col = ['DESIGNATION','POSTED DATE', 'LOCATION','EXPERIENCE']
sample_df = pd.DataFrame(columns = col)
page = requests.get("https://www.hcltech.com/careers/Careers-in-india")
soup = BeautifulSoup(page.text, 'html.parser')
for t in soup.find_all(name='table', attrs={'class':'views-table cols-4 table table-hover table-striped'}):
    l=t.find_all(name='td', attrs={'class':'views-field views-field-field-kenexa-jobs-designation'})
    job_post=[]
    for i in range(len(l)):
        s=str(l[i]).replace('</a>','')
        s1=s.replace('</td>','')
        s2=s1[s1.rfind(">")+1:]
        s3=s2.replace("\n","")
        job_post.append(s3)
    sample_df['DESIGNATION']=job_post
    job_post=[]
    m=t.find_all(name='td',attrs={'class':'views-field views-field-field-kenxa-jobs-updated-date'})
    for i in range(len(m)):
        s=str(m[i]).replace('</span>','')
        s1=s.replace('</td>','')
        s2=s1[s1.rfind(">")+1:]
        s3=s2.replace("\n","")
        job_post.append(s3)
    sample_df['POSTED DATE']=job_post
    job_post=[]
    n=t.find_all(name='td',attrs={'class':'views-field views-field-field-kenexa-jobs-location'})
    for i in range(len(n)):
        s1=str(n[i]).replace('</td>','')
        s2=s1[s1.rfind(">")+1:]
        s3=s2.replace("\n","")
        s4=s3.replace(" ",'')
        job_post.append(s4)
    sample_df['LOCATION']=job_post   
    job_post=[]
    b=t.find_all(name='td',attrs={'class':'views-field views-field-field-kenexa-experience-range'})
    for i in range(len(b)):
        s1=str(b[i]).replace('</td>','')
        s2=s1[s1.rfind(">")+1:]
        s3=s2.replace("\n","")
        s4=s3.replace(" ",'')
        job_post.append(s4)
    sample_df['EXPERIENCE']=job_post    
print(sample_df)

                               DESIGNATION    POSTED DATE LOCATION EXPERIENCE
0                          Technical Lead   Sep 23, 2020   Chennai   5-8Years
1                           Lead Engineer   Sep 23, 2020   Chennai   5-7Years
2         Customer Service Representative   Sep 22, 2020     Noida    Fresher
3  Senior Customer Service Representative   Sep 22, 2020     Noida   1-3Years
4                       Process Associate   Sep 22, 2020     Noida    Fresher
5                          Technical Lead   Sep 21, 2020     Noida   5-8Years

In [84]:
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pds
import time

col=['job name','job city']
sample_df = pd.DataFrame(columns = col)
page = requests.get("https://www.flipkartcareers.com/#!/joblist")
soup = BeautifulSoup(page.text, 'html.parser')
t=soup.find_all(name='div',attrs={'class':'job-title-div ng-binding'})
print(t)

[]